version: "3"
services:
  ukim-ctf-db:
    image: "postgres"
    container_name: "ukim-ctf-db"
    environment:
      - POSTGRES_USER=jovan
      - POSTGRES_PASSWORD=jovan
      - POSTGRES_DB=test
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data      
